### ISSUE TITLE
The app load all of my apps and then crash

### ISSUE THREAD

**Issue by GlitchedCod** [RikkaApps/App-Ops-issue-tracker#122]
I don't know if this is the same issue that was sended the 31 March but maybe with more details it can help.

### System info: / 系统信息：
For being able to get the "Copy info" I used a trick to stop the app before it crash opening the left layout, click on the top bar and press "Reselect working mode" so that the app stop loading the list of app that make him crash. So the "(Rinku)" was added by me.

Android Version: 11 (API 30)
Device: Xiaomi M2102J20SG
App Version: 5.5.2.r1435.8c176946.G (1435)
Installer: com.android.vending
Working Mode: (Rinku)
Working Profile: yes (current: 0)

Crash logs from Xiaomi:
```
android.content.res.Resources$NotFoundException: Plural resource ID #0x7f0f0000 quantity=3 item=other
	at android.content.res.ResourcesImpl.getQuantityText(ResourcesImpl.java:326)
	at android.content.res.Resources.getQuantityText(Resources.java:533)
	at android.content.res.Resources.getQuantityString(Resources.java:609)
	at rikka.appops.da.没收感叹号(SourceFile:15)
	at rikka.appops.g8.不可以(SourceFile:21)
	at androidx.lifecycle.LiveData.好饿呀(SourceFile:6)
	at androidx.lifecycle.LiveData.没收星星月亮小熊抱枕(SourceFile:8)
	at rikka.appops.t50.诶诶诶(SourceFile:4)
	at androidx.lifecycle.LiveData$a.run(SourceFile:5)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

### What did you do? / 你做了什么？
Start the app, it load every apps and then when he finished the app crash.

### What did you expect to see? / 你期望看到什么？
A list of app.

### What did you see instead? / 然而你实际上得到的却是？
My home launcher.

**Comment by RikkaW** [comment]
What language are you using? The localization file for French is broken.

**Comment by GlitchedCod** [comment]
The problem was solved with the English localisation file. Does the file will be fixed for French translation ? I can help to fix it.
Thanks, have a nice day.

**Comment by RikkaW** [comment]
This version should fix the issue. https://github.com/RikkaApps/App-Ops-issue-tracker/releases/download/files/appops-v5.5.4.r1441.e04f23be.apk
