### ISSUE TITLE
无法对三星安全文件丈夹下的用户重设为系统默认

### ISSUE THREAD

**Issue by wpecker** [RikkaApps/App-Ops-issue-tracker#138]
### System info: / 系统信息：

Android Version: 13 (API 33)
Device: samsung SM-F9360
App Version: 9.0.2.r1675.fcf1f288 (1675)
Installer: com.google.android.packageinstaller
Working Mode: Shizuku V3 (13)
Working Profile: yes (current: 0)
Alipay order id: 2022112222001437381420282871

### What did you do? / 你做了什么？

对三星安全文件夹下的应用 ”重设为系统默认” 会崩溃掉

### What did you expect to see? / 你期望看到什么？

重设为系统默认成功

### What did you see instead? / 然而你实际上得到的却是？

Shell does not have permission to access user 150
 com.android.server.am.ActivityManagerService.handleIncomingUser:14929 android.app.ActivityManager.handleIncomingUser:4802 com.android.server.appop.AppOpsService.resetAllModes:3088 

java.lang.SecurityException: Shell does not have permission to access user 150
 com.android.server.am.ActivityManagerService.handleIncomingUser:14929 android.app.ActivityManager.handleIncomingUser:4802 com.android.server.appop.AppOpsService.resetAllModes:3088 
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.os.Parcel.readException(Parcel.java:2932)
	at com.android.internal.app.IAppOpsService$Stub$Proxy.resetAllModes(IAppOpsService.java:1733)
	at rikka.appops.ea.没收桌子(Unknown Source:8)
	at rikka.appops.j4.resetAllModes(SourceFile:1)
	at rikka.appops.jh0$a.invokeSuspend(SourceFile:16)
	at rikka.appops.if.resumeWith(SourceFile:6)
	at rikka.appops.dr.run(SourceFile:109)
	at rikka.appops.r80.run(SourceFile:13)
	at rikka.appops.gy0.run(SourceFile:3)
	at rikka.appops.xn$a.run(SourceFile:82)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2672)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:14929)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:4802)
	at com.android.server.appop.AppOpsService.resetAllModes(AppOpsService.java:3088)
	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:889)

**Comment by RikkaW** [comment]
如提示所说 Shell does not have permission to access user 150，Shell（adb）没有权限（
