### ISSUE TITLE
对话框提示"Something is wrong"，无法获取绝大多数应用申请的权限

### ISSUE THREAD

**Issue by DebuAqua** [RikkaApps/App-Ops-issue-tracker#73]
### System info: / 系统信息：

Android Version: 10 (API 29)
Device: Xiaomi Mi MIX 2
App Version: 5.0.2.r1236.b614cceb (1236)
Installer: com.android.vending
Working Mode: Shizuku V3 (10)
Working Profile: no (current: 0)
Google token: ifkiomlomiglljglkllpebcm.AO-J1OwRTX-dLpsklVrVmAsT0WU_iJ85F2bDu2LxbpYd8czscOXOaOCJ66CjhMhUZElkFb95ZNuFTnyX10WL-NfW-SLTKkP-QhWPVTwLcnDgMmCbLKqsBrs

### What did you do? / 你做了什么？

硬件：小米MIX2
操作系统：lineage 17.1，nightly版本，发布于2020/08/27
Root方式为Magisk
有OpenGapps提供的谷歌框架
App Ops运行在Shizuku模式
已安装存储空间隔离及开启其增强模式的Riru模块

### What did you expect to see? / 你期望看到什么？

App Ops 可以枚举每一个应用申请的权限，并能正常地控制权限

### What did you see instead? / 然而你实际上得到的却是？

App Ops无法获得绝大多数应用申请的权限，当然也不能控制权限访问。

可以正常控制权限的程序有：
com.authy.authy
com.e2esoft.ivcam
io.github.domi04151309.powerapp

对绝大多数应用程序，均会弹出错误提示：
Something is wrong
You can send an error message to us by mail to help us solve the problem

Stacktrace内容：
No virtual method getDuration()I in class Landroid/app/AppOpsManager$OpEntry; or its super classes (declaration of 'android.app.AppOpsManager$OpEntry' appears in /system/framework/framework.jar)

java.lang.NoSuchMethodError: No virtual method getDuration()I in class Landroid/app/AppOpsManager$OpEntry; or its super classes (declaration of 'android.app.AppOpsManager$OpEntry' appears in /system/framework/framework.jar)
	at rikka.appops.qr.变身时间只要零点零一秒的粉红色魔法少女(ErrorLogHelper.java:1)
	at rikka.appops.ss0.G(Unknown Source:11)
	at rikka.appops.s51.只是路过的魔法少女(ApiImplShizuku.kt:3)
	at rikka.appops.ss0.f(Unknown Source:4)
	at rikka.appops.s51.没收舌头(ApiImplShizuku.kt:1)
	at rikka.appops.a01.牙膏回收(PackageOpsLiveData.kt:3)
	at rikka.appops.a01.好耶(PackageOpsLiveData.kt:2)
	at rikka.appops.a01$b$a.invokeSuspend(PackageOpsLiveData.kt:2)
	at rikka.appops.k70.resumeWith(ContinuationImpl.kt:2)
	at rikka.appops.wb0.run(DispatchedTask.kt:17)
	at rikka.appops.ge0.牙膏回收(CoroutineScheduler.kt:1)
	at rikka.appops.ge0$a.run(CoroutineScheduler.kt:13)

**Comment by RikkaW** [comment]
Already solved in v5.0.3
