### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by sbmatch** [RikkaApps/App-Ops-issue-tracker#81]
### System info: / 系统信息：

Android Version: 11 (API 30)
Device: Xiaomi Redmi K30 Pro
App Version: 5.1.3.r1316.812bbe6c (1316)
Installer: com.android.vending
Working Mode: Shizuku V3 (10)
Working Profile: yes (current: 0)
Google token: ggdgkialodbafalcdcgojhfm.AO-J1OxZOq5Mvcipb0n9WWCLdC2p5yoJxOhOm5y4ZLk3kKfNENnjSMBSo0hw1GUb3PvHWlvE1zG9OIzp4g5uq2RVtt6jl8SDpBuDS3eLnZyltu4jBZc4f0Y

### What did you do? / 你做了什么？

重启手机

### What did you expect to see? / 你期望看到什么？
appops在后台自动运行

### What did you see instead? / 然而你实际上得到的却是？
系统报错：appops停止运行 
log：
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ad565c3 u0 rikka.appops/.monitor.RecoveryService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2074)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by RikkaW** [comment]
如果是偶尔出现就当不存在（
