### ISSUE TITLE
套用模板时应用已卸载

### ISSUE THREAD

**Issue by x7890** [RikkaApps/App-Ops-issue-tracker#9]
安装完新应用，然后软件自动开始套用模板。此时手动卸载应用。卸载完毕，通知栏会保留正在套用模板的提示，无法清除。使用场景：完成下载APP并打开的任务，然后卸载应用。

**Comment by x7890** [comment]
刚才还出现这样的崩溃信息：
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
	at rikka.appops.service.WorkService.onHandleIntent(WorkService.java:133)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by RikkaW** [comment]
这两个情况都好神奇..
试着简单修了了一下 等过几天发了 2.3.0 试一下 吧..（
